language: c
install:
- wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
- bash -ex .travis-opam.sh
- bash -ex .travis-docgen.sh
os:
- linux
- osx
env:
  matrix:
  - OCAML_VERSION=4.03 PACKAGE=sqlite3 KEEP=1
  global:
  - secure: W5wAsspXvOtSqRqSV8qS/Bi6tNXxcXgdiCiO+KFq0bp90wQe/uTKySeKB51P2JLaPFu9phYW3MIt+ziZsx+3Rx6Lpgl10mRDxM6toPV7CxhyH3GidbLtghk4sLHlwQqCgYfEYih1DP/rXp2DjZgzrFBVFF/g1mHcrWc+bPBtLe4=
